[mysql]
  dbname  = "todo"
  host    = "localhost"
  port    = 3306
  user    = "development"
  pass    = "password"
  sslmode = "false"
  whitelist = [
    "todos"
  ]
  blacklist = [
    "schema_migrations"
  ]