node-tools-install:
	npm install -g @bufbuild/buf @bufbuild/protoc-gen-connect-es @bufbuild/protoc-gen-es && \
	npm install @bufbuild/connect @bufbuild/connect-web @bufbuild/protobuf

set-path:
	echo "export PATH=$PATH:`npm prefix --location=global`/bin" >> ~/.zshrc